<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
    <body>
    <div class="container-fluid">
            <h1 class="h1">Bitcoin Price</h1>
        <div class="col-xs-12 col-sm-4">
            <button type="button" class="btn btn-success btn-lg ">
                Asia <br/>
                THB <?php echo number_format($th[1]['last_price'], 2); ?> <br/>
                    <?php echo number_format($th[1]['change'], 2); ?>
            </button>
        </div>
        <div class="col-xs-12 col-sm-4">
            <button type="button" class="btn btn-danger btn-lg  ">
                Europe <br/>
                EUR <?php echo number_format($coindesk['bpi']['EUR']['rate_float'], 2); ?> <br/>
                    <?php echo number_format($th[1]['change'], 2); ?>
            </button>
        </div>
        <div class="col-xs-12 col-sm-4">
            <button type="button" class="btn btn-success btn-lg ">
                Americas <br/>
                USD <?php echo number_format($coindesk['bpi']['USD']['rate_float'], 2); ?> <br/>
                    <?php echo number_format($th[1]['change'], 2); ?>
            </button>
        </div>
    </div>
    </body>
</html>