<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Grypto - Around The World Market Comparison</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"/>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>
    <div class="container-fluid">
            <h1 class="h1">GRPTO</h1>
            <h5 class="pull-right">Coming Soon</h5>
            <div class="col-xs-12 col-sm-4">
                <button type="button" class="btn btn-success btn-lg btn-block">
                    Asia <br/>
                    THB <?php echo number_format($th[1]['last_price'], 2); ?> <br/>
                        <?php echo number_format($th[1]['change'], 2); ?>
                </button>
            </div>
        <div class="row"><div class="col-xs-12"></div> </div>
            <div class="col-xs-12 col-sm-4">
                <button type="button" class="btn btn-danger btn-lg btn-block ">
                    Europe <br/>
                    EUR <?php echo number_format($coindesk['bpi']['EUR']['rate_float'], 2); ?> <br/>
                        <?php echo number_format($th[1]['change'], 2); ?>
                </button>
            </div>
        <div class="row"><div class="col-xs-12"></div> </div>
            <div class="col-xs-12 col-sm-4">
                <button type="button" class="btn btn-success btn-lg btn-block">
                    Americas <br/>
                    USD <?php echo number_format($coindesk['bpi']['USD']['rate_float'], 2); ?> <br/>
                        <?php echo number_format($th[1]['change'], 2); ?>
                </button>
            </div>
        </div>
    </body>
</html>